# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.emsa.europa.eu:
  peer0.dma.dk:
  peer1.dma.dk:
  peer0.veeteedeamet.ee:
  peer1.veeteedeamet.ee:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dma.dk-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/aca652f87f250edca00722840d48634f149a0e19e35b0ba53d7e4e0f5bf7a3a7_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dma.dk-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/aca652f87f250edca00722840d48634f149a0e19e35b0ba53d7e4e0f5bf7a3a7_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/dma.dk/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.veeteedeamet.ee-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e2082674ce0606246384a7c611abbd5570795cdd040c66679142698c732677c0_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.veeteedeamet.ee-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e2082674ce0606246384a7c611abbd5570795cdd040c66679142698c732677c0_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/veeteedeamet.ee/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn

  orderer.emsa.europa.eu:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.emsa.europa.eu
    container_name: orderer.emsa.europa.eu
    networks:
      - byfn

  peer0.dma.dk:
    container_name: peer0.dma.dk
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.dma.dk
    networks:
      - byfn

  peer1.dma.dk:
    container_name: peer1.dma.dk
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.dma.dk
    networks:
      - byfn

  peer0.veeteedeamet.ee:
    container_name: peer0.veeteedeamet.ee
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.veeteedeamet.ee
    networks:
      - byfn

  peer1.veeteedeamet.ee:
    container_name: peer1.veeteedeamet.ee
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.veeteedeamet.ee
    networks:
      - byfn
