version: '2'

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    hostname: ipfs_host
    volumes:
    - "./ipfs-docker-staging:/export"
    - "./ipfs-docker-data:/data/ipfs"
    ports:
    - "5001:5001"
    - "4001:4001"
    - "8080:8080"