# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.emsa.europa.eu:
    container_name: orderer.emsa.europa.eu
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/emsa.europa.eu/orderers/orderer.emsa.europa.eu/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/emsa.europa.eu/orderers/orderer.emsa.europa.eu/tls/:/var/hyperledger/orderer/tls
        - orderer.emsa.europa.eu:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.dma.dk:
    container_name: peer0.dma.dk
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dma.dk
      - CORE_PEER_ADDRESS=peer0.dma.dk:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dma.dk:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dma.dk:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dma.dk:7051
      - CORE_PEER_LOCALMSPID=DmaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dma.dk/peers/peer0.dma.dk/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dma.dk/peers/peer0.dma.dk/tls:/etc/hyperledger/fabric/tls
        - peer0.dma.dk:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.dma.dk:
    container_name: peer1.dma.dk
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.dma.dk
      - CORE_PEER_ADDRESS=peer1.dma.dk:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.dma.dk:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dma.dk:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dma.dk:7051
      - CORE_PEER_LOCALMSPID=DmaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dma.dk/peers/peer1.dma.dk/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dma.dk/peers/peer1.dma.dk/tls:/etc/hyperledger/fabric/tls
        - peer1.dma.dk:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.veeteedeamet.ee:
    container_name: peer0.veeteedeamet.ee
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.veeteedeamet.ee
      - CORE_PEER_ADDRESS=peer0.veeteedeamet.ee:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.veeteedeamet.ee:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.veeteedeamet.ee:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.veeteedeamet.ee:10051
      - CORE_PEER_LOCALMSPID=VtaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/veeteedeamet.ee/peers/peer0.veeteedeamet.ee/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/veeteedeamet.ee/peers/peer0.veeteedeamet.ee/tls:/etc/hyperledger/fabric/tls
        - peer0.veeteedeamet.ee:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.veeteedeamet.ee:
    container_name: peer1.veeteedeamet.ee
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.veeteedeamet.ee
      - CORE_PEER_ADDRESS=peer1.veeteedeamet.ee:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.veeteedeamet.ee:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.veeteedeamet.ee:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.veeteedeamet.ee:9051
      - CORE_PEER_LOCALMSPID=VtaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/veeteedeamet.ee/peers/peer1.veeteedeamet.ee/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/veeteedeamet.ee/peers/peer1.veeteedeamet.ee/tls:/etc/hyperledger/fabric/tls
        - peer1.veeteedeamet.ee:/var/hyperledger/production
    ports:
      - 10051:10051
